name: Release

on:
  workflow_dispatch:

jobs:
  build-simc:
    runs-on: macos-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'simulationcraft/simc'
          
      - name: Extract Simc Version info and setup output information
        id: simc_info
        env:
          configHeader: engine/config.hpp
        run: |
          export SIMC_MAJOR=$(grep -E -e "^#define SC_MAJOR_VERSION" "${{ env.configHeader }}" | sed -E -e "s/#define SC_MAJOR_VERSION \"([0-9]+)\"/\1/g")
          export SIMC_MINOR=$(grep -E -e "^#define SC_MINOR_VERSION" "${{ env.configHeader }}" | sed -E -e "s/#define SC_MINOR_VERSION \"([0-9]+)\"/\1/g")
          export SIMC_VERSION=$SIMC_MAJOR-$SIMC_MINOR
          echo "::set-output name=simc_version::$(echo "$SIMC_VERSION")"
          echo "::set-output name=simc_output_file::$(echo "simc-$SIMC_VERSION-osx-x86.dmg")"
          echo "::set-output name=simc_nightly_file::$(echo "simc-$SIMC_VERSION-${{ matrix.architecture }}-${{ steps.git_hash.outputs.sha_short }}.dmg")"
          echo "$SIMC_VERSION" > ./simc-version
      
      - name: Build CLI
        run: ./engine/make optimized

      - uses: actions/upload-artifact@v2
        with:
          name: simc-artifact-macos
          path: ./simc
        
  package-ui-macos:
    runs-on: macos-latest
    needs: [build-simc]
    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - uses: actions/download-artifact@v2
        with:
          name: simc-artifact-macos
          path: packages/simcui-app/resouces/bin

      - name: Create Package
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn app postinstall && yarn app package-mac

      - uses: actions/upload-artifact@v2
        with:
          name: package-artifact-macos
          path: |
            packages/simcui-app/release/*.dmg
